version: "3"
name: pgvector-blogchat
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogvector
